#!/usr/bin/env bash
# Sourced by run.sh. Branch-focused fixtures from docs/engineering-rules-audit.md.

hook_field() { printf '%s' "$2" | bash "$PACK/shared/hooks/$1" 2>/dev/null | jq -r "$3" 2>/dev/null || echo "none"; }
shell_perm() { hook_field before_shell.sh "$1" '.permission // "none"'; }
read_perm() { hook_field before_read_file.sh "$1" '.permission // "none"'; }

echo ""
echo "=== Audit: shell source-write paths with spaces/quotes ==="
run_test "denies redirect into double-quoted path with space" "deny" "$(shell_perm '{"command":"echo hi > \"my file.ts\""}')"
run_test "denies redirect into single-quoted path with space" "deny" "$(shell_perm "{\"command\":\"echo hi > 'my file.py'\"}")"
run_test "denies redirect into backslash-escaped space path" "deny" "$(shell_perm '{"command":"echo hi > my\\\\ file.ts"}')"
run_test "denies tee into quoted path with space" "deny" "$(shell_perm '{"command":"tee \"src/my comp.tsx\""}')"
run_test "denies cp onto quoted source path" "deny" "$(shell_perm '{"command":"cp a.txt \"src/x y.go\""}')"
run_test "denies heredoc redirect (cat <<EOF > x.ts)" "deny" "$(shell_perm '{"command":"cat <<EOF > src/x.ts\nx\nEOF"}')"
run_test "allows redirect into non-source file" "allow" "$(shell_perm '{"command":"echo hi > notes.txt"}')"
run_test "allows redirect into quoted non-source path" "allow" "$(shell_perm '{"command":"echo hi > \"my notes.md\""}')"
run_test "allows grep on .ts files (no write)" "allow" "$(shell_perm '{"command":"grep -rn foo src/app.ts"}')"

echo ""
echo "=== Audit: destructive rm scope ==="
run_test "denies rm -rf /" "deny" "$(shell_perm '{"command":"rm -rf /"}')"
run_test "denies rm -rf /*" "deny" "$(shell_perm '{"command":"rm -rf /*"}')"
run_test "denies quoted rm -rf \"/\"" "deny" "$(shell_perm '{"command":"rm -rf \"/\""}')"
run_test "denies sudo rm -rf /" "deny" "$(shell_perm '{"command":"sudo rm -rf /"}')"
run_test "denies rm -r -f /" "deny" "$(shell_perm '{"command":"rm -r -f /"}')"
run_test "denies rm -fr /var" "deny" "$(shell_perm '{"command":"rm -fr /var"}')"
run_test "denies rm -rf /usr" "deny" "$(shell_perm '{"command":"rm -rf /usr"}')"
run_test "denies rm -rf ~" "deny" "$(shell_perm '{"command":"rm -rf ~"}')"
run_test "denies rm -rf ~/Documents" "deny" "$(shell_perm '{"command":"rm -rf ~/Documents"}')"
run_test "denies rm -rf \$HOME" "deny" "$(shell_perm '{"command":"rm -rf $HOME"}')"
run_test "denies rm -rf ." "deny" "$(shell_perm '{"command":"rm -rf ."}')"
run_test "denies rm -rf .." "deny" "$(shell_perm '{"command":"rm -rf .."}')"
run_test "allows rm -rf /tmp/kleos-x (ordinary temp cleanup)" "allow" "$(shell_perm '{"command":"rm -rf /tmp/kleos-x"}')"
run_test "allows rm -rf ./dist" "allow" "$(shell_perm '{"command":"rm -rf ./dist"}')"
run_test "allows rm -rf node_modules" "allow" "$(shell_perm '{"command":"rm -rf node_modules"}')"
run_test "allows rm -rf dist/ build/" "allow" "$(shell_perm '{"command":"rm -rf dist/ build/"}')"

echo ""
echo "=== Audit: malformed / missing payload, missing dependency ==="
run_test "before_shell: non-JSON payload → ask (never silent allow)" "ask" "$(shell_perm 'not json')"
run_test "before_shell: JSON without command → ask" "ask" "$(shell_perm '{"foo":"bar"}')"
run_test "before_shell: empty stdin → ask" "ask" "$(shell_perm '')"
MSG="$(hook_field before_shell.sh 'not json' '.user_message // ""')"
run_test "before_shell: ask carries an actionable message" "1" "$(printf '%s' "$MSG" | grep -c 'doctor' || true)"
run_test "before_read_file: non-JSON payload → deny (failClosed contract)" "deny" "$(read_perm 'not json')"
MSG="$(hook_field before_read_file.sh 'not json' '.user_message // ""')"
run_test "before_read_file: deny carries an actionable message" "1" "$(printf '%s' "$MSG" | grep -c 'doctor' || true)"
run_test "before_read_file: normal path → explicit allow" "allow" "$(read_perm '{"file_path":"/home/u/src/app.ts"}')"
run_test "before_read_file: path with spaces + secret suffix → deny" "deny" "$(read_perm '{"file_path":"/home/u/my dir/server.key"}')"
RESULT="$(hook_field before_submit_prompt.sh 'not json' '.continue')"
run_test "before_submit_prompt: non-JSON payload → continue:false" "false" "$RESULT"
RESULT="$(hook_field session_start.sh 'not json' 'type')"
run_test "session_start: non-JSON payload still emits an object" "object" "$RESULT"

NOPOL="$(mktemp -d "${TMPDIR:-/tmp}/kleos-nopol.XXXXXX")"
mkdir -p "$NOPOL/lib"
cp "$PACK/shared/hooks/before_read_file.sh" "$NOPOL/"
cp "$PACK/shared/hooks/lib/common.sh" "$NOPOL/lib/"
RESULT="$(printf '%s' '{"file_path":"/x/.env"}' | bash "$NOPOL/before_read_file.sh" 2>/dev/null | jq -r '.permission // "none"' 2>/dev/null || echo none)"
run_test "before_read_file: missing secret_paths.ere → deny (no silent allow)" "deny" "$RESULT"
rm -rf "$NOPOL"

FAKEBIN="$(mktemp -d "${TMPDIR:-/tmp}/kleos-nojq.XXXXXX")"
printf '#!/usr/bin/env bash\nexit 127\n' > "$FAKEBIN/jq"
chmod +x "$FAKEBIN/jq"
RESULT="$(printf '%s' '{"command":"ls"}' | PATH="$FAKEBIN:$PATH" bash "$PACK/shared/hooks/before_shell.sh" 2>/dev/null; echo "exit=$?")"
run_test "before_shell: broken jq → no fabricated allow (empty stdout, non-zero exit)" "exit=127" "$RESULT"
RESULT="$(printf '%s' '{"file_path":"/x/.env"}' | PATH="$FAKEBIN:$PATH" bash "$PACK/shared/hooks/before_read_file.sh" 2>/dev/null; echo "exit=$?")"
run_test "before_read_file: broken jq → non-zero exit (Cursor failClosed denies)" "exit=127" "$RESULT"
rm -rf "$FAKEBIN"

echo ""
echo "=== Audit: hooks leave no state behind ==="
WS="$(mktemp -d "${TMPDIR:-/tmp}/kleos-ws.XXXXXX")"
printf '# NOW\n\n## Now\n\nx\n' >"$WS/NOW.md"
PAYLOAD="$(jq -n --arg wr "$WS" '{hook_event_name:"sessionStart",composer_mode:"agent",conversation_id:"c1",workspace_roots:[$wr]}')"
printf '%s\n' "$PAYLOAD" | bash "$PACK/shared/hooks/session_start.sh" >/dev/null 2>&1
run_test "session_start does not create state/ in the workspace" "no" "$([[ -e "$WS/state" ]] && echo yes || echo no)"
rm -rf "$WS"
run_test "no hook created state/ in the pack" "no" "$([[ -e "$PACK/state" ]] && echo yes || echo no)"

echo ""
echo "=== Audit: registry shape ==="
for j in hooks.json hooks.cloud.json; do
  RESULT="$(jq -r '[.hooks[][] | (.timeout // "missing")] | map(tostring) | join(",")' "$PACK/shared/hooks/$j")"
  run_test "$j: every hook has a numeric timeout" "0" "$(printf '%s' "$RESULT" | grep -c missing || true)"
done
run_test "exactly one AGENTS.md (no nested @import adapters)" "1" "$(find "$PACK" -name AGENTS.md -not -path '*/.git/*' -not -path '*/node_modules/*' | wc -l | tr -d ' ')"
run_test "no CLAUDE.md / .cursorrules / .claude (no consumer)" "0" "$(find "$PACK" \( -name CLAUDE.md -o -name .cursorrules -o -name .claude \) -not -path '*/.git/*' | wc -l | tr -d ' ')"
run_test "shell_fleet.sh removed (dead bypass)" "no" "$([[ -e "$PACK/shared/hooks/lib/shell_fleet.sh" ]] && echo yes || echo no)"
run_test "no runtime/installer reference to shell_fleet remains" "0" "$(grep -RIl 'shell_fleet' "$PACK/shared" "$PACK/Windows" "$PACK/MacOS" "$PACK/Linux" "$PACK/README.md" 2>/dev/null | wc -l | tr -d ' ')"

echo ""
echo "=== Audit: install twice + uninstall (fake HOME) ==="
IH="$(mktemp -d "${TMPDIR:-/tmp}/kleos-idem.XXXXXX")"
mkdir -p "$IH/.cursor/rules" "$IH/.cursor/skills/foreign-skill" "$IH/.cursor/agents"
printf '%s\n' '---' 'alwaysApply: true' '---' '# mine' > "$IH/.cursor/rules/foreign.mdc"
printf '# foreign\n' > "$IH/.cursor/skills/foreign-skill/SKILL.md"
printf '# foreign agent\n' > "$IH/.cursor/agents/foreign.md"
HOME="$IH" FORCE=1 bash "$PACK/shared/hooks/fleet_sync.sh" install >/dev/null 2>&1
FIRST="$(cd "$IH" && find .cursor -not -path '*/.git*' | LC_ALL=C sort | tr '\n' ' ')"
HOME="$IH" FORCE=1 bash "$PACK/shared/hooks/fleet_sync.sh" install >/dev/null 2>&1
SECOND="$(cd "$IH" && find .cursor -not -path '*/.git*' | LC_ALL=C sort | tr '\n' ' ')"
run_test "install twice yields identical ~/.cursor tree" "same" "$([[ "$FIRST" == "$SECOND" ]] && echo same || echo differs)"
run_test "install does not create ~/.cursor/state" "no" "$([[ -e "$IH/.cursor/state" ]] && echo yes || echo no)"
RESULT="$(HOME="$IH" bash "$PACK/shared/hooks/fleet_sync.sh" uninstall >/dev/null 2>&1; echo $?)"
run_test "fleet_sync uninstall exits 0" "0" "$RESULT"
run_test "uninstall removes ~/.cursor/hooks.json" "no" "$([[ -e "$IH/.cursor/hooks.json" ]] && echo yes || echo no)"
run_test "uninstall removes ~/.cursor/hooks/" "no" "$([[ -e "$IH/.cursor/hooks" ]] && echo yes || echo no)"
run_test "uninstall removes pack rules (ponytail.mdc)" "no" "$([[ -e "$IH/.cursor/rules/ponytail.mdc" ]] && echo yes || echo no)"
run_test "uninstall removes pack skill symlink (ponytail)" "no" "$([[ -e "$IH/.cursor/skills/ponytail" || -L "$IH/.cursor/skills/ponytail" ]] && echo yes || echo no)"
run_test "uninstall removes pack agents (hunter.md)" "no" "$([[ -e "$IH/.cursor/agents/hunter.md" ]] && echo yes || echo no)"
run_test "uninstall keeps foreign rule" "yes" "$([[ -f "$IH/.cursor/rules/foreign.mdc" ]] && echo yes || echo no)"
run_test "uninstall keeps foreign skill" "yes" "$([[ -f "$IH/.cursor/skills/foreign-skill/SKILL.md" ]] && echo yes || echo no)"
run_test "uninstall keeps foreign agent" "yes" "$([[ -f "$IH/.cursor/agents/foreign.md" ]] && echo yes || echo no)"
RESULT="$(HOME="$IH" bash "$PACK/shared/hooks/fleet_sync.sh" uninstall >/dev/null 2>&1; echo $?)"
run_test "uninstall twice is idempotent (exit 0)" "0" "$RESULT"
printf '{"version":1,"hooks":{"stop":[{"command":"./hooks/other.sh"}]}}\n' > "$IH/.cursor/hooks.json"
HOME="$IH" bash "$PACK/shared/hooks/fleet_sync.sh" uninstall >/dev/null 2>&1
run_test "uninstall leaves a hooks.json it does not own" "yes" "$([[ -f "$IH/.cursor/hooks.json" ]] && echo yes || echo no)"
rm -rf "$IH"
run_test "uninstall did not touch the pack .cursor beyond types.mdc" "no" "$([[ -e "$PACK/.cursor/hooks.json" ]] && echo yes || echo no)"
